### PR TITLE
added option to install MMPM in MagicMirror installation script

### PR DESCRIPTION
**Pull request by Bee-Mar**
Thank you for creating and maintaining all the MagicMirror installation scripts! This pull request adds the option for a user to install [MMPM](https://github.com/Bee-Mar/mmpm) at the time of installing MagicMirror itself. 

All the whitespace removal was done automatically due to my Vim configuration, so don't think anything of that.

Please let me know if you have any questions or suggestions for the pull request I've submitted.

Thanks!

### CODE REVIEW

**Comment by sdetweil** [comment]
it would be interesting to search github for modules with mmm- names and word magicmirror or mirror in their title description..  vs using  the 3rd party list which isn't maintained very much.
also you could get age of last change commit, for freshness..  I haven't use mmpm..

**Comment by sdetweil** [comment]
all output should go to the logfile

**Comment by Bee-Mar** [comment]
@sdetweil I'll make those changes, and push to the branch. Feel free to install MMPM and see how you like it.

**Comment by Bee-Mar** [comment]
@sdetweil Just added in the logging. Let me know if you would like anything else added/removed

**Comment by sdetweil** [comment]
wouldn't you redirect all the make output to a file in case of problems? or just to keep the noise down and toss them if all is ok?

**Comment by Bee-Mar** [comment]
@sdetweil If you'd prefer it be redirected in your script, I can do that. During the installation of MMPM, the python modules sometimes take a while to build on a raspberry pi, and have left it to printed to stdout so the user is aware the processes are running vs just hanging/failing

**Comment by Bee-Mar** [comment]
@sdetweil , MMPM has been modified heavily, and is now available on PyPI. The installation method has changed, and is much simpler as well.

**Comment by Bee-Mar** [comment]
@sdetweil is this merge request no longer of interest?

**Comment by sdetweil** [comment]
just been watching to see what interest there is in MMPM 

it doesn't help my scripted mission to reduce manual interactions to get & maintain MM runtime status.

**Comment by Bee-Mar** [comment]
@sdetweil have you tried out the new version? there's been significant changes

**Comment by sdetweil** [comment]
sorry. I have not. w my knee surgery lots of things need time

**Comment by Bee-Mar** [comment]
@sdetweil not a problem. Feel free to try out 2.02, it's available now, and the difference will be extremely noticeable. The CLI commands are now similar to Ubuntu/Debian's `apt`

**Pull request closed without merging**
